server:
  port: 8080

spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3307/taotao?characterEncoding=UTF-8
    username: root2
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存
    cache: false

